package kaz.olzhas.ylab.entity.types;

public enum ActionType {
    REGISTRATION,
    AUTHORIZATION,
    BOOK_WORKSPACE,
    CREATE_WORKSPACE,
    ADD_WORKSPACE,
    ADD_USER,
    SHOW_RESERVATIONS,
    DELETE_RESERVATION,
    GET_AVAILABLE_SLOTS,
    SHOW_AVAILABLE_WORKSPACES,
    SHOW_ALL_WORKSPACES,
    SHOW_ALL_USERS,
    BOOKINGS_BY_USER,
    BOOKINGS_BY_WORKSPACE
}
