datasource:
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: o130805o
  url: jdbc:postgresql://localhost:5433/coworking-service-db
liquibase:
  enabled: true
  change-log: db/main-changelog.xml
  liquibase-schema: liquibase